CREATE TABLE oauth_accounts
(
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  deleted_at TIMESTAMP WITHOUT TIME ZONE,
  uid        VARCHAR(255)                            NOT NULL,
  provider VARCHAR(100) NOT NULL,
  provider_id VARCHAR(255) NOT NULL,
  user_id    VARCHAR(128)                            NOT NULL,
  CONSTRAINT pk_oauth_accounts PRIMARY KEY (id)
);

ALTER TABLE oauth_accounts
  ADD CONSTRAINT uc_oauth_accounts_uid UNIQUE (uid);
