CREATE TABLE oauth_accounts
(
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  deleted_at TIMESTAMP WITHOUT TIME ZONE,
  provider   VARCHAR(100)                            NOT NULL,
  provider_id VARCHAR(255)                           NOT NULL,
  user_id    BIGINT                            NOT NULL,
  CONSTRAINT pk_oauth_accounts PRIMARY KEY (id)
);


ALTER TABLE oauth_accounts
  ADD CONSTRAINT uk_provider_pid UNIQUE (provider, provider_id);

ALTER TABLE oauth_accounts
  ADD CONSTRAINT uk_user_provider UNIQUE (user_id, provider);

ALTER TABLE users
  ALTER COLUMN password DROP NOT NULL;
