CREATE TABLE ai_advices
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    uid        VARCHAR(255)                            NOT NULL,
    user_id    VARCHAR(128)                            NOT NULL,
    goal_id    VARCHAR(128),
    prompt_id  VARCHAR(128)                            NOT NULL,
    template_uid VARCHAR(128)                          NOT NULL,
    success    BOOLEAN                                 NOT NULL,
    error_message VARCHAR(1000),
    advice_content TEXT,
    CONSTRAINT pk_ai_advices PRIMARY KEY (id)
);

ALTER TABLE ai_advices
    ADD CONSTRAINT uc_ai_advices_uid UNIQUE (uid);

CREATE INDEX idx_ai_advices_user_id ON ai_advices(user_id);
CREATE INDEX idx_ai_advices_goal_id ON ai_advices(goal_id);
CREATE INDEX idx_ai_advices_created_at ON ai_advices(created_at);
