-- Create retrospect_kpts table
CREATE TABLE retrospect_kpts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    retrospect_id BIGINT NOT NULL,
    keep VARCHAR(500) NOT NULL,
    problem VARCHAR(500) NOT NULL,
    try_next VARCHAR(500) NOT NULL,
    CONSTRAINT pk_retrospect_kpts PRIMARY KEY (id)
);

-- Add foreign key constraint
ALTER TABLE retrospect_kpts 
    ADD CONSTRAINT fk_retrospect_kpts_retrospect_id 
    FOREIGN KEY (retrospect_id) REFERENCES retrospects (id);

-- Add unique constraint on retrospect_id
ALTER TABLE retrospect_kpts 
    ADD CONSTRAINT uc_retrospect_kpts_retrospect_id 
    UNIQUE (retrospect_id);