CREATE TABLE promotions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    uid        VARCHAR(255)                            NOT NULL,
    code       VARCHAR(255)                            NOT NULL,
    type       VARCHAR(50)                             NOT NULL,
    expired_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_active  BOOLEAN DEFAULT TRUE                    NOT NULL,
    CONSTRAINT pk_promotions PRIMARY KEY (id)
);

ALTER TABLE promotions
    ADD CONSTRAINT uc_promotions_uid UNIQUE (uid);

ALTER TABLE promotions
    ADD CONSTRAINT uc_promotions_code UNIQUE (code);