CREATE TABLE user_promotion_map
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    user_id      VARCHAR(255)                            NOT NULL,
    promotion_id VARCHAR(255)                            NOT NULL,
    used_at      TIMESTAMP WITHOUT TIME ZONE,
    is_used      BOOLEAN DEFAULT FALSE                   NOT NULL,
    CONSTRAINT pk_user_promotion_map PRIMARY KEY (id)
);

ALTER TABLE user_promotion_map
    ADD CONSTRAINT uc_user_promotion_map_user_promotion UNIQUE (user_id, promotion_id);