CREATE TABLE goals
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    uid        VARCHAR(255)                            NOT NULL,
    user_id    VARCHAR(128)                            NOT NULL,
    name       VARCHAR(128)                            NOT NULL,
    start_date date                                    NOT NULL,
    end_date   date                                    NOT NULL,
    as_is      VARCHAR(128)                            NOT NULL,
    to_be      VARCHAR(128)                            NOT NULL,
    CONSTRAINT pk_goals PRIMARY KEY (id)
);

CREATE TABLE jobrole
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    uid        VARCHAR(255)                            NOT NULL,
    name       VARCHAR(32)                             NOT NULL,
    CONSTRAINT pk_jobrole PRIMARY KEY (id)
);

INSERT INTO jobrole (id, created_at, updated_at, name, uid, deleted_at) VALUES
                                                                          (1, '2025-06-21 22:44:05.000000', '2025-06-21 22:44:03.000000', '기획자', '6rOg7Zmp7IOd', null),
                                                                          (2, '2025-06-21 22:45:03.000000', '2025-06-21 22:45:01.000000', '디자이너', '64yA7Iqk7J207YqE', null),
                                                                          (3, '2025-06-21 22:45:30.000000', '2025-06-21 22:45:41.000000', '개발자', '6rCE7J2067O07YqE', null);


CREATE TABLE plans
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    uid           VARCHAR(255)                            NOT NULL,
    week_of_month INTEGER                                 NOT NULL,
    content       VARCHAR(128)                            NOT NULL,
    start_date    date                                    NOT NULL,
    end_date      date                                    NOT NULL,
    goal_id       BIGINT,
    CONSTRAINT pk_plans PRIMARY KEY (id)
);

CREATE TABLE retrospects
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    uid        VARCHAR(255)                            NOT NULL,
    user_id    VARCHAR(128)                            NOT NULL,
    goal_id    VARCHAR(128)                            NOT NULL,
    plan_id    VARCHAR(128)                            NOT NULL,
    content    VARCHAR(500)                            NOT NULL,
    CONSTRAINT pk_retrospects PRIMARY KEY (id)
);

CREATE TABLE todos
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    uid          VARCHAR(255)                            NOT NULL,
    user_id      VARCHAR(128)                            NOT NULL,
    plan_id      VARCHAR(255)                            NOT NULL,
    goal_id      VARCHAR(255)                            NOT NULL,
    date         date                                    NOT NULL,
    content      VARCHAR(255)                            NOT NULL,
    is_completed BOOLEAN DEFAULT FALSE                   NOT NULL,
    CONSTRAINT pk_todos PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    uid         VARCHAR(255)                            NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    job_role_id VARCHAR(255)                            NOT NULL,
    career_year VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE goals
    ADD CONSTRAINT uc_goals_uid UNIQUE (uid);

ALTER TABLE jobrole
    ADD CONSTRAINT uc_jobrole_uid UNIQUE (uid);

ALTER TABLE plans
    ADD CONSTRAINT uc_plans_uid UNIQUE (uid);

ALTER TABLE retrospects
    ADD CONSTRAINT uc_retrospects_planid UNIQUE (plan_id);

ALTER TABLE retrospects
    ADD CONSTRAINT uc_retrospects_uid UNIQUE (uid);

ALTER TABLE todos
    ADD CONSTRAINT uc_todos_uid UNIQUE (uid);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_uid UNIQUE (uid);

ALTER TABLE plans
    ADD CONSTRAINT FK_PLANS_ON_GOAL FOREIGN KEY (goal_id) REFERENCES goals (id);
