CREATE TABLE chat_advice
(
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  deleted_at      TIMESTAMP WITHOUT TIME ZONE,
  user_id         VARCHAR(255)                            NOT NULL,
  remaining_count INTEGER                                 NOT NULL,
  last_reset_date date                                    NOT NULL,
  conversations   JSONB,
  CONSTRAINT pk_chat_advice PRIMARY KEY (id)
);

CREATE TABLE user_advice_status
(
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  deleted_at     TIMESTAMP WITHOUT TIME ZONE,
  user_id        VARCHAR(255)                            NOT NULL,
  last_seen_date date,
  CONSTRAINT pk_user_advice_status PRIMARY KEY (id)
);

ALTER TABLE chat_advice
  ADD CONSTRAINT uc_chat_advice_user UNIQUE (user_id);

ALTER TABLE user_advice_status
  ADD CONSTRAINT uc_user_advice_status_user UNIQUE (user_id);

