CREATE TABLE routines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    user_id VARCHAR(128) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    repeat_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    PRIMARY KEY (id)
);

-- Add index on user_id for better query performance
CREATE INDEX idx_routines_user_id ON routines(user_id);

-- Add index on uid for unique lookups
CREATE INDEX idx_routines_uid ON routines(uid);

-- Add index on start_date and end_date for date range queries
CREATE INDEX idx_routines_dates ON routines(start_date, end_date);

-- Add index on deleted_at for soft delete queries
CREATE INDEX idx_routines_deleted_at ON routines(deleted_at);

-- Create trigger function to update updated_at column
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger for updated_at
CREATE TRIGGER update_routines_updated_at BEFORE UPDATE ON routines FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();