ALTER TABLE todos ALTER COLUMN category TYPE VARCHAR(16);

UPDATE todos
SET category = CASE category
    WHEN 'NOW' THEN 'URGENT'
    WHEN 'STEADY' THEN 'CONSISTENT'
    WHEN 'SKIP' THEN 'DEFERABLE'
    WHEN 'DELETE' THEN 'DELETABLE'
    ELSE category
END;

ALTER TABLE todos ALTER COLUMN category SET DEFAULT 'URGENT';
