CREATE TABLE user_tokens
(
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uid        VARCHAR(255)                            NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  deleted_at TIMESTAMP WITHOUT TIME ZONE,
  token      VARCHAR(512)                            NOT NULL,
  user_id    VARCHAR(255)                            NOT NULL,
  CONSTRAINT pk_user_tokens PRIMARY KEY (id)
);

ALTER TABLE user_tokens
  ADD CONSTRAINT uc_user_tokens_token UNIQUE (token);

ALTER TABLE user_tokens
  ADD CONSTRAINT uc_user_tokens_uid UNIQUE (uid);

ALTER TABLE sayings RENAME COLUMN "from" TO author;
