CREATE TABLE goal_retrospects
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at           TIMESTAMP WITHOUT TIME ZONE,
    uid                  VARCHAR(255)                            NOT NULL,
    goal_id              VARCHAR(255)                            NOT NULL,
    todo_completed_rate  INTEGER                                 NOT NULL,
    analysis_summary     VARCHAR(1000)                           NOT NULL,
    analysis_advice      VARCHAR(1000)                           NOT NULL,
    content              VARCHAR(1000)                           NOT NULL,
    CONSTRAINT pk_goal_retrospects PRIMARY KEY (id)
);

ALTER TABLE goal_retrospects
    ADD CONSTRAINT uc_goal_retrospects_uid UNIQUE (uid);

ALTER TABLE goal_retrospects
    ADD CONSTRAINT uc_goal_retrospects_goal_id UNIQUE (goal_id);