CREATE TABLE missions
(
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  deleted_at TIMESTAMP WITHOUT TIME ZONE,
  uid        VARCHAR(255)                            NOT NULL,
  finished   BOOLEAN                                 NOT NULL,
  content    VARCHAR(255)                            NOT NULL,
  user_id    VARCHAR(128)                            NOT NULL,
  CONSTRAINT pk_missions PRIMARY KEY (id)
);

ALTER TABLE missions
  ADD CONSTRAINT uc_missions_uid UNIQUE (uid);
