openapi: 3.0.1
info:
  title: GrowIT API Specification
  description: GrowIT description
  version: 0.0.2
servers:
- url: http://growit-alb-alb-549641300.ap-northeast-2.elb.amazonaws.com/
tags: []
paths: {}
components:
  schemas: {}
