package com.growit.app.user.domain.token.service;

import com.growit.app.common.config.oauth.KakaoKeys;
import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.jwk.source.RemoteJWKSet;
import com.nimbusds.jose.proc.JWSVerificationKeySelector;
import com.nimbusds.jose.proc.SecurityContext;
import com.nimbusds.jwt.JWTClaimsSet;
import com.nimbusds.jwt.proc.ConfigurableJWTProcessor;
import com.nimbusds.jwt.proc.DefaultJWTProcessor;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.ParseException;
import java.util.Map;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

@Slf4j
@Component
public class KakaoIdTokenValidator {

  private static final RemoteJWKSet<SecurityContext> KAKAO_JWKS;

  static {
    try {
      KAKAO_JWKS = new RemoteJWKSet<>(new URL("https://kauth.kakao.com/.well-known/jwks.json"));
    } catch (MalformedURLException e) {
      throw new IllegalStateException("Invalid Kakao JWKS URL", e);
    }
  }

  @Value("${app.oauth.kakao.client-id}")
  private String clientId;

  /**
   * Parses and verifies the Kakao OIDC id_token.
   *
   * <p>Validates: RS256 signature (JWKS), iss, aud, exp (by DefaultJWTProcessor), nonce.
   *
   * @param idToken Kakao id_token JWT
   * @param nonce nonce value generated by the frontend and included in the login request
   * @return verified JWT claims
   */
  public Map<String, Object> parseAndVerifyIdToken(String idToken, String nonce) {
    try {
      ConfigurableJWTProcessor<SecurityContext> processor = new DefaultJWTProcessor<>();
      processor.setJWSKeySelector(new JWSVerificationKeySelector<>(JWSAlgorithm.RS256, KAKAO_JWKS));

      JWTClaimsSet claims = processor.process(idToken, null);

      if (!KakaoKeys.ISSUER.equals(claims.getIssuer())) {
        throw new IllegalStateException("Invalid Kakao ID Token issuer");
      }

      if (!claims.getAudience().contains(clientId)) {
        throw new IllegalStateException("Invalid Kakao ID Token audience");
      }

      String tokenNonce = (String) claims.getClaim(KakaoKeys.NONCE);
      if (tokenNonce == null || !tokenNonce.equals(nonce)) {
        throw new IllegalStateException("Invalid Kakao ID Token nonce");
      }

      return claims.getClaims();
    } catch (ParseException e) {
      log.error("Failed to parse Kakao id_token", e);
      throw new IllegalArgumentException("Invalid Kakao id_token format");
    } catch (IllegalArgumentException | IllegalStateException e) {
      throw e;
    } catch (Exception e) {
      log.error("Failed to verify Kakao id_token signature via JWKS", e);
      throw new IllegalStateException("Kakao id_token verification failed");
    }
  }
}
